
package desafio;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author juan
 */


/**
 *
 Clase que actúa como un menú principal desde el que se accede al resto del programa
 */
public class Pantalla extends javax.swing.JFrame {

  private String usuarioActual;
  int xMouse, yMouse; //estas variables servirán para localizar la posición del ratón
  
    /**
     *
     */
    public Pantalla() {
        initComponents();
        this.setSize(469, 548);
        this.setLocationRelativeTo(null); //con esto la pantalla saldrá centrada
        obtenerUsuarioActual();
        
    }
    
    
    // Método para obtener el nombre de usuario actual
    private void obtenerUsuarioActual() {
        usuarioActual = Login.getUsuario(); // Asignar el valor de usuario actual a la variable de instancia
        if (usuarioActual == null || usuarioActual.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el nombre de usuario actual.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogOpcionesLista = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOpcionVistas = new javax.swing.JButton();
        btnOpcionQuieroVer = new javax.swing.JButton();
        btnOpcionFavoritas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCatalogo = new javax.swing.JButton();
        btnListas = new javax.swing.JButton();
        lblMiCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnMiCuenta1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        dialogOpcionesLista.setFocusable(false);
        dialogOpcionesLista.setMinimumSize(new java.awt.Dimension(409, 119));
        dialogOpcionesLista.setResizable(false);
        dialogOpcionesLista.setSize(new java.awt.Dimension(409, 119));
        dialogOpcionesLista.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setText("Elige una lista");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, 20));

        btnOpcionVistas.setBackground(new java.awt.Color(0, 204, 153));
        btnOpcionVistas.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnOpcionVistas.setText("Vistas");
        btnOpcionVistas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcionVistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionVistas.setFocusable(false);
        btnOpcionVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionVistasActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpcionVistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 30));

        btnOpcionQuieroVer.setBackground(new java.awt.Color(0, 204, 255));
        btnOpcionQuieroVer.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnOpcionQuieroVer.setText("Quiero ver");
        btnOpcionQuieroVer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcionQuieroVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionQuieroVer.setFocusable(false);
        btnOpcionQuieroVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionQuieroVerActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpcionQuieroVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 80, 30));

        btnOpcionFavoritas.setBackground(new java.awt.Color(255, 255, 153));
        btnOpcionFavoritas.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnOpcionFavoritas.setText("Favoritas");
        btnOpcionFavoritas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcionFavoritas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionFavoritas.setFocusable(false);
        btnOpcionFavoritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionFavoritasActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpcionFavoritas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 80, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quiero_ver_pequeño.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vistas_pequeño.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favoritas_pequeño.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 60, 30, 30));

        dialogOpcionesLista.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 120));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(469, 554));
        setMinimumSize(new java.awt.Dimension(469, 554));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(469, 554));
        setResizable(false);
        setSize(new java.awt.Dimension(469, 554));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/theater.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, 90));

        btnCatalogo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnCatalogo.setText("CATÁLOGO");
        btnCatalogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCatalogo.setContentAreaFilled(false);
        btnCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogo.setFocusable(false);
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 40));

        btnListas.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnListas.setText("MIS LISTAS");
        btnListas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListas.setContentAreaFilled(false);
        btnListas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListas.setFocusable(false);
        btnListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListasActionPerformed(evt);
            }
        });
        jPanel1.add(btnListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, 40));

        lblMiCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jPanel1.add(lblMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movies.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/list.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoff.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 40, 40));

        btnSalir.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnSalir.setText("CERRAR SESIÓN");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 140, 40));

        btnMiCuenta1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnMiCuenta1.setText("MI CUENTA");
        btnMiCuenta1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMiCuenta1.setContentAreaFilled(false);
        btnMiCuenta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMiCuenta1.setFocusable(false);
        btnMiCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMiCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tira_pelicula.png"))); // NOI18N
        lblFondo.setText("jLabel1");
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 550));

        jPanel3.setOpaque(false);
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        Catalogo catalogo = new Catalogo(null, true);
        catalogo.setVisible(true);
        
       
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListasActionPerformed
     
        dialogOpcionesLista.setSize(400,205);
        dialogOpcionesLista.setLocationRelativeTo(null);
        dialogOpcionesLista.setVisible(true);                              

    }//GEN-LAST:event_btnListasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Login login = new Login();
        login.setCursor(null); //esto debería evitar que el cursor aparezca en un elemento por defecto
        login.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnOpcionVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionVistasActionPerformed
        ListaVistas listavistas = new ListaVistas(null,true);
        listavistas.setVisible(true);
    }//GEN-LAST:event_btnOpcionVistasActionPerformed

    private void btnOpcionQuieroVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionQuieroVerActionPerformed
        ListaQuieroVer listaquierover = new ListaQuieroVer(null,true);
        listaquierover.setVisible(true);
    }//GEN-LAST:event_btnOpcionQuieroVerActionPerformed

    private void btnOpcionFavoritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionFavoritasActionPerformed
        ListaFavoritas listafavoritas = new ListaFavoritas(null,true);
        listafavoritas.setVisible(true);
    }//GEN-LAST:event_btnOpcionFavoritasActionPerformed

    private void btnMiCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiCuenta1ActionPerformed
        MiCuenta micuenta = new MiCuenta(null, true);
        micuenta.setVisible(true);
    }//GEN-LAST:event_btnMiCuenta1ActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    


    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnListas;
    private javax.swing.JButton btnMiCuenta1;
    private javax.swing.JButton btnOpcionFavoritas;
    private javax.swing.JButton btnOpcionQuieroVer;
    private javax.swing.JButton btnOpcionVistas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDialog dialogOpcionesLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMiCuenta;
    // End of variables declaration//GEN-END:variables
}
